import { useEffect, useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { BookCatalog } from './components/BookCatalog';
import { BrandMark } from './components/BrandMark';
import { QrCard } from './components/QrCard';
import { Schedule } from './components/Schedule';
import { SectionHeading } from './components/SectionHeading';
import { calendar, campaigns, gatheringSteps, links, mentorTraining, packingList, parentExpectations, permissionForms, pmaExpectations, resources, studentExpectations, supplies } from './data/content';
import './styles.css';

function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => {
    const update = () => document.documentElement.style.setProperty('--progress', `${window.scrollY / Math.max(1, document.documentElement.scrollHeight - innerHeight) * 100}%`);
    addEventListener('scroll', update, { passive: true }); update(); return () => removeEventListener('scroll', update);
  }, []);

  return <main>
    <div className="progress" />
    <nav className="nav"><a className="brand" href="#top"><BrandMark /><span>RAINDROP <b>EDUCATION</b></span></a><button className="menu-button" aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>☰</button><div className={`nav-links ${menuOpen ? 'open' : ''}`}>{[['Contact', '#contact'], ['Expectations', '#expectations'], ['Calendar', '#calendar'], ['Books', '#books'], ['Forms', '#forms'], ['Payment & Support', '#payments']].map(([label, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}</div></nav>

    <header className="hero" id="top"><div className="orb orb-one"/><div className="orb orb-two"/><BrandMark /><p className="hero-kicker">RAINDROP EDUCATION · 2026–2027</p><h1>Middle School<br/><em>Open House</em></h1><p>An educational journey strengthened by mentorship, family partnership, and consistent follow-up.</p><a className="pill-button" href="#contact">Explore the Program ↓</a><div className="hero-qr"><QRCodeSVG value={links.website} size={116} level="M"/><div><strong>Open on Your Phone</strong><span>Scan the QR code</span><a href={links.website}>raindrop-open-house.pages.dev</a></div></div></header>

    <section className="section white" id="contact"><div className="wrap"><SectionHeading eyebrow="First Step" title="QR Codes and Contact" copy="Join the WhatsApp group for your grade. For questions, contact your group mentor first and Erdal Abi when needed."/><div className="contact-grid"><QrCard label="7th Grade Parent Group" image="/assets/whatsapp-7th.png"/><QrCard label="8th Grade Parent Group" image="/assets/whatsapp-8th.png"/><article className="contact-card"><span>03</span><h3>Coordinator Contact</h3><dl><div><dt>Name</dt><dd>Erdal Abi</dd></div><div><dt>Phone</dt><dd>(945) 232-3044</dd></div></dl><a className="dark-button" href="tel:+19452323044">Call ↗</a></article></div></div></section>

    <section className="section cream" id="expectations"><div className="wrap"><SectionHeading eyebrow="Parent–Mentor Partnership" title="What We Expect from Parents" copy="Mentorship extends beyond the weekend program; safe drop-off, open communication, and support at home are all parts of the same effort."/><div className="check-grid">{parentExpectations.map((item, i) => <article className="check-card" key={item}><span>{String(i + 1).padStart(2, '0')}</span><p>{item}</p></article>)}</div></div></section>

    <section className="section navy"><div className="wrap"><SectionHeading light eyebrow="Home Entry & Program Etiquette" title="What We Expect from Students" copy="Every program begins at the door with respect and a sense of responsibility."/><div className="student-grid">{studentExpectations.map(([title, copy], i) => <article className="student-card" key={title}><span>{String(i + 1).padStart(2, '0')}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="phone-alert"><strong>×</strong><div><span>PHONE POLICY</span><h3>Phones should not be brought to programs or camps.</h3><p>If a phone is brought, it will be given to the mentor and returned at the end of the program.</p></div></div></div></section>

    <section className="section white"><div className="wrap"><SectionHeading eyebrow="Curriculum & Resources" title="We read, discuss, and grow together." copy="Weekly discussion and khutbah content is delivered through MentorPortal, while individual Turkish reading assignments are managed through kitapokuyorum."/><div className="three-grid">{[['Curriculum Reading', 'Curriculum books are discussed interactively with mentors during programs.'], ['Independent Reading', 'Each student receives a level-appropriate book and weekly follow-up.'], ['Discussion & Khutbah', 'Connected weekly topics use discussion, presentations, and video content.']].map(([title, copy], i) => <article className="feature-card" key={title}><span>{String(i + 1).padStart(2, '0')}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="resources"><div><span className="eyebrow">Our Resources</span><h3>Trusted content, shared language.</h3></div><div>{resources.map(([name, href], i) => <a href={href} target="_blank" rel="noreferrer" key={name}><b>{String(i + 1).padStart(2, '0')}</b>{name}<small>Open ↗</small></a>)}</div></div></div></section>

    <section className="section teal"><div className="wrap split"><div><SectionHeading light eyebrow="Qur’an Academy" title="Consistent Qur’an Education at the Right Level" copy="After a level assessment, students are placed in appropriate Qur’an classes. Three groups began instruction last year."/><div className="stats">{[['3', 'Groups started last year'], ['1:1', 'Level-based placement'], ['∞', 'Continuous growth']].map(([n,l]) => <div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div></div><div className="arch"><BrandMark/><strong>Read · Understand · Live</strong></div></div></section>

    <section className="section white" id="calendar"><div className="wrap"><SectionHeading eyebrow="Annual Calendar" title="The roadmap for the year is ready." copy="Key dates are listed below. Open the annual calendar for complete details."/><a className="dark-button download" href="/annual-calendar.pdf" target="_blank" rel="noreferrer">Open Annual Calendar ↗</a><div className="timeline">{calendar.map(([date,title,copy]) => <article key={`${date}-${title}`}><time>{date}</time><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div><Schedule/></div></section>

    <section className="section navy"><div className="wrap"><SectionHeading light eyebrow="Beyond the Calendar" title="Monthly Gatherings" copy="Friday–Saturday and Saturday–Sunday groups meet together once each month."/><div className="flow-grid">{gatheringSteps.map((item, i) => <article key={item}><span>{String(i + 1).padStart(2, '0')}</span><p>{item}</p></article>)}</div></div></section>

    <section className="section cream" id="books"><div className="wrap"><SectionHeading eyebrow="Reading Program" title="A new book each month, a new perspective with every book." copy="Books are explored interactively with mentors during the programs."/><BookCatalog/><p className="center-note">Independent reading books are assigned through <a href="https://kitapokuyorum.org/">kitapokuyorum</a> and followed by the mentor.</p></div></section>

    <section className="section white"><div className="wrap"><SectionHeading eyebrow="Campaigns & Tracking" title="We welcome sacred seasons with purpose and enthusiasm." copy="Campaigns make positive habits visible, motivate students, and celebrate progress."/><div className="campaign-grid">{campaigns.map((item, i) => <article key={item}><span>{String(i + 1).padStart(2, '0')}</span><h3>{item}</h3><p>Programs, tracking, and recognition encourage active student participation.</p></article>)}</div></div></section>

    <section className="section navy"><div className="wrap split"><div><SectionHeading light eyebrow="Progress Tracking" title="Consistent tracking makes growth visible." copy="Qur’an, reading, homework, prayers, dhikr, and fasting goals are followed on a monthly tracker."/></div><div className="tracker"><header><strong>Monthly Tracker</strong><span>Sample View</span></header>{['Qur’an','Reading','Homework','Prayer','Dhikr'].map((item,row) => <div className="tracker-row" key={item}><span>{item}</span><div>{Array.from({length:7},(_,i)=><i key={i} className={(i + row) % 3 !== 1 ? 'checked' : ''}>{(i + row) % 3 !== 1 ? '✓' : ''}</i>)}</div></div>)}</div></div></section>

    <section className="section white"><div className="wrap"><SectionHeading eyebrow="Safe Mentorship" title="Our mentors receive training." copy="Training through MentorPortal supports a safe and informed mentorship environment."/><div className="four-grid">{mentorTraining.map((item,i)=><article className="feature-card" key={item}><span>{String(i+1).padStart(2,'0')}</span><h3>{item}</h3><p>Training and policy awareness</p></article>)}</div></div></section>

    <section className="section cream"><div className="wrap"><SectionHeading eyebrow="What to Bring" title="Packing List" copy="Essentials that help students participate comfortably and stay organized."/><div className="two-grid">{packingList.map(([title,copy],i)=><article className="white-card" key={title}><span>{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

    <section className="section teal"><div className="wrap"><SectionHeading light eyebrow="Parents–Mentor Association" title="PMA: A Strong Bridge Between Families and Mentors" copy="PMA brings communication, spiritual support at home, campaign and camp coordination, and parent education into one shared system."/><div className="pma-grid"><div className="pma-levels">{[['General PMA Representative','Overall middle school coordination'],['Grade PMA Representatives','Grade-level follow-up and reporting'],['Group PMA Representatives','Consistent parent–mentor communication']].map(([a,b],i)=><div key={a}><span>{String(i+1).padStart(2,'0')}</span><strong>{a}</strong><small>{b}</small></div>)}</div><article className="pma-list"><h3>What We Expect from PMA Parents</h3>{pmaExpectations.map(item=><p key={item}>✓ {item}</p>)}</article></div></div></section>

    <section className="section light" id="forms"><div className="wrap"><SectionHeading eyebrow="Permission Slips" title="Permission Forms" copy="Access all five permission forms through one link."/><div className="permission-layout"><div>{permissionForms.map((item,i)=><article className="permission-item" key={item}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{item}</h3><p>Available through one form link</p></div></article>)}</div><QrCard label="All Permission Forms" image="/assets/permission-forms-qr.png" caption="Scan the QR code or use the button below."/></div><a className="dark-button centered" href={links.forms} target="_blank" rel="noreferrer">Open Forms ↗</a></div></section>

    <section className="section navy" id="payments"><div className="wrap"><SectionHeading light eyebrow="Payment" title="Book and Camp Payments" copy="Pay the book fee by QR code and complete camp registration through the link or QR code."/><div className="payment-grid"><article><span>QR READY</span><h3>Annual Book Fee</h3><strong>$85</strong><img src="/assets/book-fee-qr.png" alt="Annual book fee payment QR code"/><p>Scan the QR code with your phone camera.</p></article><article><span>REGISTRATION OPEN</span><h3>Camp Fee</h3><strong>$500</strong><QRCodeSVG value={links.camp} size={190}/><p>Open the winter camp registration page.</p><a href={links.camp} target="_blank" rel="noreferrer">Open Registration ↗</a></article></div></div></section>

    <section className="section cream"><div className="wrap"><SectionHeading eyebrow="Support Our Weekend Program Homes" title="Twelve homes welcome 250 students every week." copy="Breakfasts, dinners, and refreshments are provided through our community’s generosity each week."/><div className="support-grid"><article className="support-card"><span>PREFERRED OPTION</span><h3>Beginning-of-Year Gift Card Support</h3><strong>$100 or more</strong><p>A one-time gift card helps mentors purchase supplies where they are needed most.</p><div className="tags"><b>Costco</b><b>Amazon</b><b>Visa Gift Card</b></div></article><article className="support-card"><span>ALTERNATIVE</span><h3>Beginning-of-Year Supply Package</h3><ul>{supplies.map(item=><li key={item}>{item}</li>)}</ul></article><article className="support-card zelle"><span>SUPPORT VIA ZELLE</span><h3>Help sustain our program homes.</h3><img src="/assets/zelle-support-qr.png" alt="Zelle support QR code"/><strong>$100+</strong></article></div><p className="breakfast-note">💛 <b>Weekly breakfast:</b> The parent assigned to dinner that week also brings Sunday breakfast. Rotations are shared in grade WhatsApp groups.</p></div></section>

    <footer><BrandMark/><p>Together</p><h2>A safe, organized, and<br/><em>blessed year.</em></h2><span>May the new school year be beneficial and blessed for us all.</span><small>Raindrop Education · Boys Middle School Open House · 2026–2027</small></footer>
  </main>;
}

export default App;
